<template>
  <div class="perm-page">
    <div class="page-head">
      <div>
        <h2 class="page-title">数据字典</h2>
        <p class="page-desc">管理系统中的字典数据，包括字典类型和字典项的增删改查。</p>
      </div>
      <div>
        <el-button size="small" icon="el-icon-plus" @click="handleAddDict">新增字典</el-button>
      </div>
    </div>

    <div class="dict-layout">
      <!-- 左侧：数据字典组列表 -->
      <div class="dict-sidebar">
        <div class="sidebar-header">
          <span class="sidebar-title">字典总数 <strong>{{ dictGroups.length }}</strong></span>
        </div>
        <div class="sidebar-list" v-loading="loading">
          <div
            v-for="group in dictGroups"
            :key="group.dictCode"
            class="dict-group-item"
            :class="{ active: selectedGroup && selectedGroup.dictCode === group.dictCode }"
            @click="selectGroup(group)"
          >
            <div class="group-info">
              <div class="group-name">{{ group.dictName }}</div>
              <div class="group-code">{{ group.dictCode }}</div>
            </div>
            <div class="group-count">{{ group.itemCount }}项</div>
          </div>
          <div v-if="!dictGroups.length" class="empty-tip">暂无字典组</div>
        </div>
      </div>

      <!-- 右侧：字典项列表 -->
      <div class="dict-content">
        <div class="content-header">
          <div class="content-title">
            <span v-if="selectedGroup">{{ selectedGroup.dictName }}</span>
            <span v-else class="placeholder">请选择字典组</span>
          </div>
          <div v-if="selectedGroup" class="content-actions">
            <el-button size="small" icon="el-icon-plus" @click="handleAddItem">新增字典项</el-button>
            <el-button size="small" icon="el-icon-edit" @click="handleEditGroup">编辑字典组</el-button>
          </div>
        </div>

        <div v-if="selectedGroup" class="content-table">
          <el-table :data="dictItems" border size="small" v-loading="loading">
            <el-table-column prop="itemCode" label="字典项编码" width="150" />
            <el-table-column prop="itemName" label="字典项名称" min-width="150" />
            <el-table-column prop="itemValue" label="字典值" width="120" />
            <el-table-column prop="sort" label="排序" width="80" align="center" />
            <el-table-column prop="status" label="状态" width="100" align="center">
              <template slot-scope="{ row }">
                <el-tag :type="row.status === '1' ? 'success' : 'danger'" size="small">
                  {{ row.status === '1' ? '启用' : '禁用' }}
                </el-tag>
              </template>
            </el-table-column>
            <el-table-column prop="remark" label="备注" min-width="180" show-overflow-tooltip />
            <el-table-column label="操作" width="150" align="center" fixed="right">
              <template slot-scope="{ row }">
                <el-button type="text" size="small" @click="handleEditItem(row)">编辑</el-button>
                <el-button type="text" size="small" style="color: #f56c6c;" @click="handleDeleteItem(row)">删除</el-button>
              </template>
            </el-table-column>
          </el-table>

          <div class="pagination-wrapper">
            <el-pagination
              :current-page="page"
              :page-size="pageSize"
              :total="dictItems.length"
              layout="total, prev, pager, next"
              @current-change="page = $event"
            />
          </div>
        </div>

        <div v-else class="empty-content">
          <i class="el-icon-document" style="font-size: 64px; color: #c0c4cc;"></i>
          <p style="color: #909399; margin-top: 16px;">请从左侧选择一个字典组查看字典项</p>
        </div>
      </div>
    </div>

    <!-- 新增/编辑字典组弹窗 -->
    <el-dialog
      :title="groupFormTitle"
      :visible.sync="groupDialogVisible"
      width="600px"
      @close="resetGroupForm"
    >
      <el-form :model="groupForm" :rules="groupRules" ref="groupForm" label-width="100px">
        <el-form-item label="字典名称" prop="dictName">
          <el-input v-model="groupForm.dictName" placeholder="请输入字典名称" @input="autoGenerateDictCode" />
        </el-form-item>
        <el-form-item label="字典编码" prop="dictCode">
          <el-input v-model="groupForm.dictCode" placeholder="根据字典名称自动生成" :disabled="isEditGroup">
            <template slot="append">
              <el-button @click="autoGenerateDictCode" icon="el-icon-refresh">生成</el-button>
            </template>
          </el-input>
          <div style="font-size: 12px; color: #909399; margin-top: 4px;">自动生成规则：中文转拼音/英文，小写下划线分隔</div>
        </el-form-item>
        <el-form-item label="字典类型" prop="dictType">
          <el-select v-model="groupForm.dictType" placeholder="请选择字典类型" style="width: 100%">
            <el-option label="系统字典" value="sys" />
            <el-option label="业务字典" value="biz" />
          </el-select>
        </el-form-item>
        <el-form-item label="状态" prop="status">
          <el-radio-group v-model="groupForm.status">
            <el-radio label="1">启用</el-radio>
            <el-radio label="0">禁用</el-radio>
          </el-radio-group>
        </el-form-item>
        <el-form-item label="备注">
          <el-input v-model="groupForm.remark" type="textarea" :rows="3" placeholder="请输入备注" />
        </el-form-item>
      </el-form>
      <div slot="footer">
        <el-button @click="groupDialogVisible = false">取消</el-button>
        <el-button type="primary" @click="submitGroupForm">确定</el-button>
      </div>
    </el-dialog>

    <!-- 新增/编辑字典项弹窗 -->
    <el-dialog
      :title="itemFormTitle"
      :visible.sync="itemDialogVisible"
      width="600px"
      @close="resetItemForm"
    >
      <el-form :model="itemForm" :rules="itemRules" ref="itemForm" label-width="100px">
        <el-form-item label="字典项名称" prop="itemName">
          <el-input v-model="itemForm.itemName" placeholder="请输入字典项名称" @input="autoGenerateItemCode" />
        </el-form-item>
        <el-form-item label="字典项编码" prop="itemCode">
          <el-input v-model="itemForm.itemCode" placeholder="根据字典项名称自动生成" :disabled="isEditItem">
            <template slot="append">
              <el-button @click="autoGenerateItemCode" icon="el-icon-refresh">生成</el-button>
            </template>
          </el-input>
          <div style="font-size: 12px; color: #909399; margin-top: 4px;">自动生成规则：中文转拼音/英文，小写下划线分隔</div>
        </el-form-item>
        <el-form-item label="字典值" prop="itemValue">
          <el-input v-model="itemForm.itemValue" placeholder="请输入字典值" />
        </el-form-item>
        <el-form-item label="排序" prop="sort">
          <el-input-number v-model="itemForm.sort" :min="1" :max="999" style="width: 100%" />
        </el-form-item>
        <el-form-item label="状态" prop="status">
          <el-radio-group v-model="itemForm.status">
            <el-radio label="1">启用</el-radio>
            <el-radio label="0">禁用</el-radio>
          </el-radio-group>
        </el-form-item>
        <el-form-item label="备注">
          <el-input v-model="itemForm.remark" type="textarea" :rows="3" placeholder="请输入备注" />
        </el-form-item>
      </el-form>
      <div slot="footer">
        <el-button @click="itemDialogVisible = false">取消</el-button>
        <el-button type="primary" @click="submitItemForm">确定</el-button>
      </div>
    </el-dialog>
  </div>
</template>

<script>
export default {
  name: "DataDictionary",
  data() {
    return {
      loading: false,
      page: 1,
      pageSize: 20,
      dictGroups: [], // 字典组列表
      dictItems: [], // 当前选中字典组的字典项列表
      selectedGroup: null, // 当前选中的字典组
      
      // 字典组表单
      groupDialogVisible: false,
      isEditGroup: false,
      groupForm: {
        dictCode: '',
        dictName: '',
        dictType: 'sys',
        status: '1',
        remark: '',
      },
      groupRules: {
        dictCode: [
          { required: true, message: '请输入字典编码', trigger: 'blur' },
          { pattern: /^[a-zA-Z_]+$/, message: '字典编码只能包含英文字母和下划线', trigger: 'blur' }
        ],
        dictName: [
          { required: true, message: '请输入字典名称', trigger: 'blur' }
        ],
        dictType: [
          { required: true, message: '请选择字典类型', trigger: 'change' }
        ],
      },
      
      // 字典项表单
      itemDialogVisible: false,
      isEditItem: false,
      itemForm: {
        itemCode: '',
        itemName: '',
        itemValue: '',
        sort: 1,
        status: '1',
        remark: '',
      },
      itemRules: {
        itemCode: [
          { required: true, message: '请输入字典项编码', trigger: 'blur' },
          { pattern: /^[a-zA-Z0-9_]+$/, message: '字典项编码只能包含英文字母、数字和下划线', trigger: 'blur' }
        ],
        itemName: [
          { required: true, message: '请输入字典项名称', trigger: 'blur' }
        ],
        itemValue: [
          { required: true, message: '请输入字典值', trigger: 'blur' }
        ],
      },
    };
  },
  computed: {
    groupFormTitle() {
      return this.isEditGroup ? '编辑字典组' : '新增字典组';
    },
    itemFormTitle() {
      return this.isEditItem ? '编辑字典项' : '新增字典项';
    },
  },
  mounted() {
    this.loadData();
  },
  methods: {
    loadData() {
      this.loading = true;
      // TODO: 从后端或 localStorage 加载数据
      setTimeout(() => {
        // 字典组数据
        this.dictGroups = [
          {
            dictCode: "user_type",
            dictName: "用户类型",
            dictType: "sys",
            status: "1",
            remark: "系统用户类型字典",
            createTime: "2024-01-01 10:00:00",
            itemCount: 3,
          },
          {
            dictCode: "gender",
            dictName: "性别",
            dictType: "sys",
            status: "1",
            remark: "用户性别字典",
            createTime: "2024-01-02 10:00:00",
            itemCount: 2,
          },
          {
            dictCode: "org_level",
            dictName: "组织级别",
            dictType: "sys",
            status: "1",
            remark: "组织机构级别字典",
            createTime: "2024-01-03 10:00:00",
            itemCount: 4,
          },
        ];

        // 默认选中第一个
        if (this.dictGroups.length > 0) {
          this.selectGroup(this.dictGroups[0]);
        }

        this.loading = false;
      }, 500);
    },
    // 选择字典组
    selectGroup(group) {
      this.selectedGroup = group;
      this.page = 1;
      this.loadDictItems(group.dictCode);
    },
    // 加载字典项数据
    loadDictItems(dictCode) {
      this.loading = true;
      // TODO: 根据 dictCode 从后端加载字典项
      setTimeout(() => {
        // 示例数据
        const mockItems = {
          user_type: [
            {
              itemCode: "user_type_admin",
              itemName: "管理员",
              itemValue: "1",
              sort: 1,
              status: "1",
              remark: "系统管理员",
            },
            {
              itemCode: "user_type_normal",
              itemName: "普通用户",
              itemValue: "2",
              sort: 2,
              status: "1",
              remark: "普通用户",
            },
            {
              itemCode: "user_type_guest",
              itemName: "访客",
              itemValue: "3",
              sort: 3,
              status: "0",
              remark: "临时访客",
            },
          ],
          gender: [
            {
              itemCode: "gender_male",
              itemName: "男",
              itemValue: "1",
              sort: 1,
              status: "1",
              remark: "男性",
            },
            {
              itemCode: "gender_female",
              itemName: "女",
              itemValue: "2",
              sort: 2,
              status: "1",
              remark: "女性",
            },
          ],
          org_level: [
            {
              itemCode: "org_level_province",
              itemName: "省级",
              itemValue: "1",
              sort: 1,
              status: "1",
              remark: "省级组织",
            },
            {
              itemCode: "org_level_city",
              itemName: "市级",
              itemValue: "2",
              sort: 2,
              status: "1",
              remark: "市级组织",
            },
            {
              itemCode: "org_level_county",
              itemName: "县级",
              itemValue: "3",
              sort: 3,
              status: "1",
              remark: "县级组织",
            },
            {
              itemCode: "org_level_unit",
              itemName: "单位级",
              itemValue: "4",
              sort: 4,
              status: "1",
              remark: "单位级组织",
            },
          ],
        };

        this.dictItems = mockItems[dictCode] || [];
        this.loading = false;
      }, 300);
    },
    // 新增字典组
    handleAddDict() {
      this.isEditGroup = false;
      this.groupDialogVisible = true;
    },
    // 编辑字典组
    handleEditGroup() {
      this.isEditGroup = true;
      Object.assign(this.groupForm, this.selectedGroup);
      this.groupDialogVisible = true;
    },
    // 新增字典项
    handleAddItem() {
      this.isEditItem = false;
      this.itemDialogVisible = true;
    },
    // 编辑字典项
    handleEditItem(row) {
      this.isEditItem = true;
      Object.assign(this.itemForm, row);
      this.itemDialogVisible = true;
    },
    // 删除字典项
    handleDeleteItem(row) {
      this.$confirm(`确定要删除字典项"${row.itemName}"吗？`, "提示", {
        confirmButtonText: "确定",
        cancelButtonText: "取消",
        type: "warning",
      }).then(() => {
        this.$message.success("删除成功");
      }).catch(() => {});
    },
    
    // 提交字典组表单
    submitGroupForm() {
      this.$refs.groupForm.validate((valid) => {
        if (valid) {
          if (this.isEditGroup) {
            // 编辑逻辑
            Object.assign(this.selectedGroup, this.groupForm);
            this.$message.success('字典组更新成功');
          } else {
            // 新增逻辑
            const newGroup = {
              ...this.groupForm,
              itemCount: 0,
              createTime: new Date().toLocaleString(),
            };
            this.dictGroups.push(newGroup);
            this.$message.success('字典组新增成功');
            // 自动选中新新增的字典组
            this.selectGroup(newGroup);
          }
          this.groupDialogVisible = false;
        }
      });
    },
    
    // 提交字典项表单
    submitItemForm() {
      this.$refs.itemForm.validate((valid) => {
        if (valid) {
          if (this.isEditItem) {
            // 编辑逻辑
            const index = this.dictItems.findIndex(item => item.itemCode === this.itemForm.itemCode);
            if (index > -1) {
              Object.assign(this.dictItems[index], this.itemForm);
            }
            this.$message.success('字典项更新成功');
          } else {
            // 新增逻辑
            const newItem = {
              ...this.itemForm,
            };
            this.dictItems.push(newItem);
            // 更新字典组的项数量
            if (this.selectedGroup) {
              this.selectedGroup.itemCount = this.dictItems.length;
            }
            this.$message.success('字典项新增成功');
          }
          this.itemDialogVisible = false;
        }
      });
    },
    
    // 重置字典组表单
    resetGroupForm() {
      this.$refs.groupForm && this.$refs.groupForm.resetFields();
      this.groupForm = {
        dictCode: '',
        dictName: '',
        dictType: 'sys',
        status: '1',
        remark: '',
      };
    },
    
    // 重置字典项表单
    resetItemForm() {
      this.$refs.itemForm && this.$refs.itemForm.resetFields();
      this.itemForm = {
        itemCode: '',
        itemName: '',
        itemValue: '',
        sort: 1,
        status: '1',
        remark: '',
      };
    },
    
    // 自动生成字典编码
    autoGenerateDictCode() {
      if (!this.groupForm.dictName || this.isEditGroup) {
        return;
      }
      
      // 常见中文词汇到英文的映射
      const commonWords = {
        '用户': 'user',
        '类型': 'type',
        '性别': 'gender',
        '组织': 'org',
        '级别': 'level',
        '状态': 'status',
        '角色': 'role',
        '部门': 'dept',
        '岗位': 'position',
        '数据': 'data',
        '范围': 'range',
        '配置': 'config',
        '管理': 'management',
        '权限': 'permission',
        '系统': 'system',
        '业务': 'business',
        '考勤': 'attendance',
        '员工': 'employee',
        '人员': 'personnel',
        '日志': 'log',
        '菜单': 'menu',
        '模块': 'module',
        '功能': 'function',
      };
      
      let name = this.groupForm.dictName;
      let code = '';
      
      // 尝试匹配常见词汇
      let matched = false;
      for (let [chinese, english] of Object.entries(commonWords)) {
        if (name.includes(chinese)) {
          code = code ? `${code}_${english}` : english;
          name = name.replace(chinese, '');
          matched = true;
        }
      }
      
      // 如果没有匹配到任何词汇，使用拼音首字母
      if (!matched || code === '') {
        // 简单的中文转拼音首字母（仅支持常见汉字）
        const pinyinMap = {
          '一': 'yi', '二': 'er', '三': 'san', '四': 'si', '五': 'wu',
          '六': 'liu', '七': 'qi', '八': 'ba', '九': 'jiu', '十': 'shi',
        };
        
        // 如果包含中文，使用拼音首字母组合
        const chineseChars = name.match(/[\u4e00-\u9fa5]/g);
        if (chineseChars) {
          const pinyinFirst = chineseChars.map(char => {
            return pinyinMap[char] || char.charCodeAt(0).toString(36);
          }).join('');
          code = code ? `${code}_${pinyinFirst}` : pinyinFirst;
        } else {
          // 如果是英文，直接转小写并替换空格
          code = name.toLowerCase().replace(/\s+/g, '_');
        }
      }
      
      // 清理编码：只保留字母、数字和下划线
      code = code.replace(/[^a-zA-Z0-9_]/g, '_');
      // 移除连续的下划线
      code = code.replace(/_+/g, '_');
      // 移除开头和结尾的下划线
      code = code.replace(/^_+|_+$/g, '');
      // 转为小写
      code = code.toLowerCase();
      
      // 如果生成的编码为空，使用默认值
      if (!code) {
        code = 'dict_' + Date.now().toString(36);
      }
      
      // 检查编码是否已存在，如果存在则添加数字后缀
      const existingCodes = this.dictGroups.map(g => g.dictCode);
      let finalCode = code;
      let suffix = 1;
      while (existingCodes.includes(finalCode)) {
        finalCode = `${code}_${suffix}`;
        suffix++;
      }
      
      this.groupForm.dictCode = finalCode;
    },
    
    // 自动生成字典项编码
    autoGenerateItemCode() {
      if (!this.itemForm.itemName || this.isEditItem) {
        return;
      }
      
      // 获取当前字典组的编码作为前缀
      const groupPrefix = this.selectedGroup ? this.selectedGroup.dictCode : 'item';
      
      // 常见中文词汇到英文的映射
      const commonWords = {
        '管理员': 'admin',
        '普通': 'normal',
        '用户': 'user',
        '访客': 'guest',
        '男': 'male',
        '女': 'female',
        '省级': 'province',
        '市级': 'city',
        '县级': 'county',
        '单位': 'unit',
        '启用': 'enable',
        '禁用': 'disable',
        '是': 'yes',
        '否': 'no',
        '成功': 'success',
        '失败': 'fail',
        '通过': 'pass',
        '拒绝': 'reject',
        '待审核': 'pending',
        '已审核': 'approved',
      };
      
      let name = this.itemForm.itemName;
      let suffix = '';
      
      // 尝试匹配常见词汇
      let matched = false;
      for (let [chinese, english] of Object.entries(commonWords)) {
        if (name.includes(chinese)) {
          suffix = suffix ? `${suffix}_${english}` : english;
          name = name.replace(chinese, '');
          matched = true;
        }
      }
      
      // 如果没有匹配到任何词汇，使用拼音
      if (!matched || suffix === '') {
        // 简单的中文转拼音（仅支持常见汉字）
        const pinyinMap = {
          '一': 'yi', '二': 'er', '三': 'san', '四': 'si', '五': 'wu',
          '六': 'liu', '七': 'qi', '八': 'ba', '九': 'jiu', '十': 'shi',
        };
        
        // 如果包含中文，使用拼音
        const chineseChars = name.match(/[\u4e00-\u9fa5]/g);
        if (chineseChars) {
          const pinyinStr = chineseChars.map(char => {
            return pinyinMap[char] || char.charCodeAt(0).toString(36);
          }).join('');
          suffix = suffix ? `${suffix}_${pinyinStr}` : pinyinStr;
        } else {
          // 如果是英文，直接转小写并替换空格
          suffix = name.toLowerCase().replace(/\s+/g, '_');
        }
      }
      
      // 组合编码：字典组编码_字典项编码
      let code = suffix ? `${groupPrefix}_${suffix}` : groupPrefix;
      
      // 清理编码：只保留字母、数字和下划线
      code = code.replace(/[^a-zA-Z0-9_]/g, '_');
      // 移除连续的下划线
      code = code.replace(/_+/g, '_');
      // 移除开头和结尾的下划线
      code = code.replace(/^_+|_+$/g, '');
      // 转为小写
      code = code.toLowerCase();
      
      // 如果生成的编码为空，使用时间戳
      if (!code) {
        code = `${groupPrefix}_${Date.now().toString(36)}`;
      }
      
      // 检查编码是否已存在，如果存在则添加数字后缀
      const existingCodes = this.dictItems.map(item => item.itemCode);
      let finalCode = code;
      let numSuffix = 1;
      while (existingCodes.includes(finalCode)) {
        finalCode = `${code}_${numSuffix}`;
        numSuffix++;
      }
      
      this.itemForm.itemCode = finalCode;
    },
  },
};
</script>

<style scoped src="../styles/permission-page.css"></style>
<style scoped>
/* 左右布局 */
.dict-layout {
  display: flex;
  gap: 16px;
  height: calc(100vh - 200px);
  margin-top: 16px;
}

/* 左侧字典组列表 */
.dict-sidebar {
  width: 300px;
  background: #fff;
  border: 1px solid #e4e7ed;
  border-radius: 4px;
  display: flex;
  flex-direction: column;
}

.sidebar-header {
  padding: 12px 16px;
  border-bottom: 1px solid #ebeef5;
  background: #f5f7fa;
}

.sidebar-title {
  font-size: 14px;
  color: #606266;
}

.sidebar-title strong {
  color: #409eff;
  margin-left: 4px;
}

.sidebar-list {
  flex: 1;
  overflow-y: auto;
  padding: 8px;
}

.dict-group-item {
  padding: 12px;
  margin-bottom: 8px;
  border: 1px solid #e4e7ed;
  border-radius: 4px;
  cursor: pointer;
  transition: all 0.3s ease;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.dict-group-item:hover {
  border-color: #b3d8ff;
  background: #ecf5ff;
}

.dict-group-item.active {
  border-color: #409eff;
  background: #ecf5ff;
}

.group-info {
  flex: 1;
}

.group-name {
  font-size: 14px;
  font-weight: 500;
  color: #303133;
  margin-bottom: 4px;
}

.group-code {
  font-size: 12px;
  color: #909399;
}

.group-count {
  font-size: 12px;
  color: #409eff;
  font-weight: 500;
  flex-shrink: 0;
}

.empty-tip {
  text-align: center;
  padding: 40px 0;
  color: #909399;
  font-size: 14px;
}

/* 右侧字典项列表 */
.dict-content {
  flex: 1;
  background: #fff;
  border: 1px solid #e4e7ed;
  border-radius: 4px;
  display: flex;
  flex-direction: column;
  overflow: hidden;
}

.content-header {
  padding: 12px 16px;
  border-bottom: 1px solid #ebeef5;
  background: #f5f7fa;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.content-title {
  font-size: 16px;
  font-weight: 600;
  color: #303133;
}

.content-title .placeholder {
  color: #909399;
  font-weight: 400;
}

.content-actions {
  display: flex;
  gap: 8px;
}

.content-table {
  flex: 1;
  overflow-y: auto;
  padding: 16px;
}

.pagination-wrapper {
  margin-top: 16px;
  text-align: right;
}

.empty-content {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  color: #c0c4cc;
}
</style>
