/**
 * 八类无感数据接入 — 字段结构定义（与业务数据字典一致）
 * 图一南网商旅通 | 图二南网智学 | 图三数认平台 | 图四人资休假
 * 图五工作票 | 图六用车管理 | 图七食堂 | 图八闸机门禁
 */

import { WORK_TICKET_FIELDS } from "./workTicketFields";

function f(en, zh, type, meaning, opts = {}) {
  return {
    en,
    zh,
    type,
    meaning,
    isPk: !!opts.isPk,
    securityLevel: opts.securityLevel || "二级",
    highlighted: !!opts.highlighted,
  };
}

/** 南网商旅通出差申请 — 完整 66 项字段（与业务数据字典一致） */
const TRAVEL_APPLY_FIELDS = [
  f("ID", "ID", "character varying", "主键标识", { isPk: true, highlighted: true }),
  f("USER_ID", "制单人ID", "character varying", "制单人用户标识", { highlighted: true }),
  f("CID", "单位ID", "character varying", "所属单位标识", { highlighted: true }),
  f("COST_ITEMID", "成本项目ID", "character varying", "成本项目标识", { highlighted: true }),
  f("TRAVELER_ID", "差旅人员ID", "character varying", "差旅人员标识", { highlighted: true }),
  f("TRAVELER_RANK_ID", "出行人职级ID", "character varying", "出行人职级标识"),
  f("TRAVEL_TYPE_ID", "出差类别ID", "character varying", "出差类别标识"),
  f("FAIL", "控制方案ID", "character varying", "控制方案标识"),
  f("FLGID", "预算科目ID", "character varying", "预算科目标识"),
  f("BUDGET_TYPE_ID", "预算类型代码", "character varying", "D-季度预算，1-专项预算"),
  f("TENANT_ID", "租户ID", "character varying", "租户标识"),
  f("REQULATION_ID", "用车制度ID", "character varying", "用车制度标识"),
  f("END_CITY", "目的地城市", "character varying", "出差目的地城市"),
  f("END_DATE", "出差结束日期", "timestamp without time zone", "行程结束日期", { highlighted: true }),
  f("START_CITY", "出发城市", "character varying", "出差出发城市", { highlighted: true }),
  f("START_DATE", "出差开始日期", "timestamp without time zone", "行程开始日期", { highlighted: true }),
  f("STATE", "审批结果状态", "character varying", "1-同意；2-驳回"),
  f("CREATE_DATE", "订单创建时间", "timestamp without time zone", "申请单创建时间"),
  f("POST_DATETIME", "提交时间", "timestamp without time zone", "提交审批时间"),
  f("TRAVEL_TYPE", "出行类别", "character varying", "公务出差/培训等出行类别"),
  f("BILL_TYPE", "单据类型", "character varying", "1-申请单；2-行程单"),
  f("DISPATCH_TYPE", "单返双返", "character varying", "单程/往返标识"),
  f("REI_TYPE", "报销类型", "character varying", "1-已报销，0-未报销"),
  f("REIMBURSE_TYPE", "出差差旅费类别", "character varying", "差旅费报销类别"),
  f("BUDGET_TYPE", "预算类型", "character varying", "预算类型描述"),
  f("UPDATE_TIME", "更新时间", "timestamp without time zone", "记录最后更新时间"),
  f("START_CITY_CODE", "出发城市编码", "character varying", "出发地城市编码"),
  f("END_CITY_CODE", "目的地城市编码", "character varying", "目的地城市编码"),
  f("APPLY_TYPE", "申请单类型", "character varying", "申请单业务类型"),
  f("IF_WEB_INTER_TRAN", "WEB接口传输标识", "character varying", "Web接口传输标志"),
  f("TRAVEL_TYPE_SPOT", "出行类别精确标识", "character varying", "出行类别是否精确到时分秒：0-否，1-是"),
  f("IS_COST_SHARE", "是否成本分摊", "character varying", "0-不分摊，1-默认分摊"),
  f("DISPATCH_STATUS", "派车状态", "character varying", "0-不派车，1-派车"),
  f("TOTAL_DATE", "出差天数", "numeric", "出差总天数", { highlighted: true }),
  f("TOTAL_CITY_COUNT", "城市总数", "numeric", "途经城市总数"),
  f("TOTAL_COUNT", "总条数", "numeric", "明细总条数"),
  f("FSZ_NUM", "费用预估金额", "numeric", "费用预估金额"),
  f("OLD_FSZ_NUM", "变更前费用预估金额", "numeric", "变更前费用预估"),
  f("REASON", "申请单事由", "text", "出差申请事由说明"),
  f("TRANSPORTATION", "交通工具", "character varying", "主要交通工具"),
  f("APRV_STEP", "审批环节", "character varying", "当前审批环节"),
  f("APRV_USER", "审批人", "character varying", "审批人姓名"),
  f("REMARK", "备注", "text", "备注信息"),
  f("TRAVELER_MOBILE_PHONE", "差旅人员电话", "character varying", "差旅人员联系电话", { highlighted: true }),
  f("TRAVELER_NAME", "差旅人员名称", "character varying", "差旅人员姓名", { highlighted: true }),
  f("TRAVELER_IDENTITY", "差旅人员身份证号", "character varying", "差旅人员身份证件号", { highlighted: true }),
  f("CAPITAL_NO", "资金分解号", "character varying", "资金分解编号"),
  f("END_VILLAGE", "目的地乡镇", "character varying", "目的地乡镇"),
  f("START_VILLAGE", "出发乡镇", "character varying", "出发乡镇"),
  f("TRAVEL_APPLY_NUM", "申请单号", "character varying", "出差申请单编号"),
  f("CHANGE_REASON", "改变原因", "text", "行程/申请变更原因"),
  f("BUDGET_PERIOD", "预算期间", "character varying", "预算所属期间"),
  f("CAPTION", "预算科目名称", "character varying", "预算科目名称"),
  f("FANAME", "控制方案名称", "character varying", "控制方案名称"),
  f("TRAVEL_RANGE", "出差范围", "character varying", "出差地理范围"),
  f("IMAGE_KEY", "上传影像业务key", "character varying", "影像业务主键"),
  f("FILE_FLOOR_ID", "影像编号", "character varying", "影像文件编号"),
  f("IS_CONFIRMED", "自动报销", "character varying", "0-未确认，1-已确认"),
  f("TRAVEL_RANGE_YN", "出差范围定制", "character varying", "出差范围云南楚雄定制标识"),
  f("TRA_TOOLS", "交通工具明细", "character varying", "交通工具信息"),
  f("REQULATION_NAME", "用车制度名称", "character varying", "用车制度名称"),
  f("SOU_TRAVEL_DATA", "供应商申请单信息", "text", "供应商侧申请单数据"),
  f("OPEN_BOOK_FLIGHT", "开启预订机票", "character varying", "0-关闭，1-开启"),
  f("TW_DATA_COLL_TIME", "ODS层插入时间", "timestamp without time zone", "ODS层数据采集时间"),
  f("TW_CREATE_NAME", "开发人员", "character varying", "数据开发人员"),
  f("TW_INSERT_TIME", "插入时间", "timestamp without time zone", "数据入库插入时间"),
];

/** 南网智学培训数据 — 完整 44 项字段（与业务数据字典一致） */
const LEARN_TRAINING_FIELDS = [
  f("TW_INSERT_TIME", "数据插入时间", "TIMESTAMP", "ODS数据插入时间"),
  f("ID", "主键", "CHARACTER VARYING", "记录主键", { isPk: true }),
  f("PROV_ORG_NAME", "省级组织名称", "CHARACTER VARYING", "省级组织名称"),
  f("EMPLOYEE_ID", "员工标识", "CHARACTER VARYING", "员工唯一标识"),
  f("COUNTY_ORG_NAME", "县(区)局组织名称", "CHARACTER VARYING", "县区局组织名称"),
  f("EMPLOYEE_NAME", "员工姓名", "CHARACTER VARYING", "参训员工姓名", { highlighted: true }),
  f("HR_ORG_ID", "人资组织ID号", "CHARACTER VARYING", "人资组织标识", { highlighted: true }),
  f("END_TIME", "培训结束时间", "TIMESTAMP(6)", "培训结束时间", { highlighted: true }),
  f("TEAM_ORG_NAME", "班组组织名称", "CHARACTER VARYING", "班组组织名称"),
  f("METHOD_NAME", "培训方式名称", "CHARACTER VARYING", "培训方式描述"),
  f("BE_ARCHIVE", "是否归档", "CHARACTER VARYING", "培训记录是否已归档"),
  f("COUNTY_ORG_CODE", "县(区)局组织编码", "CHARACTER VARYING", "县区局组织编码"),
  f("PERIOD_NUM", "培训学时", "NUMERIC(30,4)", "本次培训学时", { highlighted: true }),
  f("REGION_ORG_CODE", "地市局组织编码", "CHARACTER VARYING", "地市局组织编码", { highlighted: true }),
  f("TW_PROVINCE_CODE", "分省分区编码", "CHARACTER VARYING", "分省分区编码", { isPk: true, highlighted: true }),
  f("COURSE_HOURS", "累计实际学时", "NUMERIC", "累计实际培训学时", { highlighted: true }),
  f("REGION_ORG_NAME", "地市局组织名称", "CHARACTER VARYING", "地市局组织名称", { highlighted: true }),
  f("METHOD_CODE", "培训方式代码", "CHARACTER VARYING", "167集中/168线上等", { highlighted: true }),
  f("DEPT_ORG_NAME", "部门(供电所)组织名称", "CHARACTER VARYING", "部门或供电所组织名称"),
  f("START_TIME", "培训开始时间", "TIMESTAMP(6)", "培训开始时间", { highlighted: true }),
  f("CSG_ORG_NAME", "网级组织名称", "CHARACTER VARYING", "网级组织名称", { highlighted: true }),
  f("PROV_ORG_CODE", "省级组织编码", "CHARACTER VARYING", "省级组织编码", { highlighted: true }),
  f("TW_PROVINCE_NAME", "分省分区单位名称", "CHARACTER VARYING", "分省分区单位名称"),
  f("SEX_CODE", "性别编码", "CHARACTER VARYING", "1男2女等性别编码"),
  f("TITLE", "培训班名称", "CHARACTER VARYING", "培训班/课程名称"),
  f("ORG_FULL_NAME", "组织名称全路径", "CHARACTER VARYING", "组织机构全路径名称"),
  f("CSG_ORG_CODE", "网级组织编码", "CHARACTER VARYING", "网级组织编码"),
  f("TEAM_ORG_CODE", "班组组织编码", "CHARACTER VARYING", "班组组织编码"),
  f("MAIN_ORG_NAME", "主办单位", "CHARACTER VARYING", "培训主办单位"),
  f("SEX_NAME", "性别名称", "CHARACTER VARYING", "性别描述"),
  f("DEPT_ORG_CODE", "部门(供电所)组织编码", "CHARACTER VARYING", "部门或供电所组织编码"),
  f("EMPLOYEE_CODE", "员工编码", "CHARACTER VARYING", "人资员工编码"),
  f("STRINGEXTEND2", "字符型扩展字段2", "CHARACTER VARYING(4000)", "字符扩展字段2"),
  f("STRINGEXTEND3", "字符型扩展字段3", "CHARACTER VARYING(4000)", "字符扩展字段3"),
  f("STRINGEXTEND4", "字符型扩展字段4", "CHARACTER VARYING(4000)", "字符扩展字段4"),
  f("STRINGEXTEND5", "字符型扩展字段5", "CHARACTER VARYING(4000)", "字符扩展字段5"),
  f("STRINGEXTEND1", "字符型扩展字段1", "CHARACTER VARYING(4000)", "字符扩展字段1"),
  f("DATEEXTEND1", "日期型扩展字段1", "TIMESTAMP", "日期扩展字段1"),
  f("DATEEXTEND2", "日期型扩展字段2", "TIMESTAMP", "日期扩展字段2"),
  f("TW_OPERATE_NAME", "运营人员", "CHARACTER VARYING", "数据运营人员"),
  f("TW_CREATE_NAME", "开发人员", "CHARACTER VARYING", "数据开发人员"),
  f("INTEXTEND3", "数值型扩展字段3", "NUMERIC", "数值扩展字段3"),
  f("INTEXTEND2", "数值型扩展字段2", "NUMERIC", "数值扩展字段2"),
  f("INTEXTEND1", "数值型扩展字段1", "NUMERIC", "数值扩展字段1"),
];

/** 人资员工休假台账 — 完整 50 项字段（与业务数据字典一致） */
const LEAVE_LEDGER_FIELDS = [
  f("DESCRIPTION", "情况说明", "VARCHAR2(2250)", "休假情况说明", { securityLevel: "一级" }),
  f("VACATION_TYPE", "休假类型", "VARCHAR2(10)", "0病假1事假2年假3探亲假4婚假5产假6陪产假7工伤假8护理假9育儿假10其他", { highlighted: true, securityLevel: "一级" }),
  f("OTHER_HOLIDAY", "其他休假类型", "VARCHAR2(80)", "0婚假1产假3其他", { highlighted: true, securityLevel: "一级" }),
  f("UNIT_ID", "所属单位ID", "VARCHAR2(40)", "所属单位标识", { highlighted: true, securityLevel: "一级" }),
  f("UNIT_NAME", "单位名称", "VARCHAR2(160)", "所属单位名称", { securityLevel: "一级" }),
  f("TEAM_ID", "班组ID", "VARCHAR2(40)", "班组标识", { securityLevel: "一级" }),
  f("TEAM_NAME", "班组名称", "VARCHAR2(80)", "班组名称", { securityLevel: "一级" }),
  f("ELINK_MSG_ID", "elink消息ID", "VARCHAR2(40)", "elink消息UUID，32位", { securityLevel: "一级" }),
  f("UPDATE_TIME", "更新时间", "TIMESTAMP(8)", "记录更新时间", { securityLevel: "一级" }),
  f("DATA_FROM", "数据来源", "VARCHAR2(160)", "数据来源系统", { securityLevel: "一级" }),
  f("DELETE_FLAG", "删除标识", "NUMBER(1)", "1未删除0已删除", { securityLevel: "一级" }),
  f("APPLY_STATUS", "请求状态", "VARCHAR2(4)", "0未提交1审核中2已审核3已退回", { securityLevel: "一级" }),
  f("HOLIDAY_WORK_AGE", "休假工龄", "NUMBER(4)", "休假相关工龄", { securityLevel: "一级" }),
  f("ORG_NAME", "单位内设机构名称", "VARCHAR2(160)", "内设机构名称", { securityLevel: "一级" }),
  f("DEPT_ID", "部门ID", "VARCHAR2(72)", "部门标识UUID，32位", { highlighted: true, securityLevel: "一级" }),
  f("POST_NAME", "岗位名称", "VARCHAR2(256)", "岗位名称", { securityLevel: "一级" }),
  f("UPDATOR_ID", "更新者ID", "VARCHAR2(72)", "最后更新人ID", { securityLevel: "一级" }),
  f("BUREAU_CODE", "局编码", "VARCHAR2(8)", "按南网信息分类编码", { securityLevel: "一级" }),
  f("CANCEL_HUMAN_HOLIDAY_ID", "销假的员工休假信息ID", "VARCHAR2(72)", "销假关联休假ID", { securityLevel: "一级" }),
  f("IN_DATE", "入本单位日期", "TIMESTAMP(8)", "进入本单位日期", { securityLevel: "一级" }),
  f("ALL_WAY_QTY", "总路途假天数", "NUMBER(4)", "路途假总天数", { securityLevel: "一级" }),
  f("OPTIMISTIC_LOCK_VERSION", "乐观锁版本", "NUMBER(12)", "乐观锁版本号", { securityLevel: "一级" }),
  f("END_DATE", "结束日期", "TIMESTAMP(8)", "休假结束日期", { securityLevel: "一级" }),
  f("CREATE_TIME", "创建时间", "TIMESTAMP(8)", "记录创建时间", { securityLevel: "一级" }),
  f("PROVINCE_CODE", "省编码", "VARCHAR2(4)", "按南网信息分类省编码", { securityLevel: "一级" }),
  f("WORK_DATE", "参加工作年月日日期", "TIMESTAMP(8)", "参加工作日期", { securityLevel: "一级" }),
  f("ALL_DATE_QTY", "总体假天数", "NUMBER(4)", "本次休假总天数", { highlighted: true, securityLevel: "一级" }),
  f("HOLIDAY_REASON", "休假原因", "VARCHAR2(4500)", "休假申请原因", { securityLevel: "一级" }),
  f("FIRM_WORK_AGE", "本企业工龄", "NUMBER(4)", "本企业工作年限", { securityLevel: "一级" }),
  f("BASEINFO_ID", "基础信息ID", "VARCHAR2(72)", "员工基础信息ID", { securityLevel: "一级" }),
  f("IS_CANCEL", "是否销假", "NUMBER(1)", "0否1是", { securityLevel: "一级" }),
  f("ID", "主键ID", "VARCHAR2(72)", "记录主键", { isPk: true, securityLevel: "一级" }),
  f("POST_ID", "岗位ID", "VARCHAR2(72)", "岗位标识", { securityLevel: "一级" }),
  f("PROCESS_INS_ID", "流程实例ID", "VARCHAR2(80)", "流程实例标识", { securityLevel: "一级" }),
  f("CREATOR_ID", "创建人ID", "VARCHAR2(72)", "创建人标识", { securityLevel: "一级" }),
  f("ORG_ID", "组织标识", "VARCHAR2(72)", "组织UUID标识", { securityLevel: "一级" }),
  f("START_DATE", "开始日期", "TIMESTAMP(8)", "休假开始日期", { securityLevel: "一级" }),
  f("FLOW_STATE", "流程状态", "NUMBER(2)", "0未提交1审核中2已审核3已退回", { securityLevel: "一级" }),
  f("DEPT_NAME", "部门名称", "VARCHAR2(300)", "部门名称", { securityLevel: "一级" }),
  f("CONFIG_ID", "休假策略ID", "VARCHAR2(40)", "休假策略配置ID", { securityLevel: "一级" }),
  f("PARENT_PROCESS_INS_ID", "父流程实例ID", "VARCHAR2(40)", "父流程实例标识", { securityLevel: "一级" }),
  f("PROCESS_DEF_NAME", "流程定义名称", "VARCHAR2(256)", "流程定义名称", { securityLevel: "一级" }),
  f("REPORTER_ID", "上报人ID", "VARCHAR2(40)", "上报人标识", { securityLevel: "一级" }),
  f("ROOT_PROCESS_INS_ID", "根流程实例ID", "VARCHAR2(40)", "根流程实例标识", { securityLevel: "一级" }),
  f("TENANT_ID", "租户ID", "VARCHAR2(128)", "多租户标识", { securityLevel: "一级" }),
  f("ALL_CANCEL_DATE_QTY", "总销假天数", "NUMBER(4)", "销假总天数", { securityLevel: "一级" }),
  f("ATTENDANCE_RULE_ID", "考勤规则ID", "VARCHAR2(600)", "关联考勤规则", { securityLevel: "一级" }),
  f("FIRST_SUBMIT_TIME", "首次提交时间", "TIMESTAMP(6)", "首次提交审批时间", { securityLevel: "一级" }),
  f("IS_HEADQUARTERS_STAFF", "是否总部员工", "NUMBER(2)", "0非总部1总部员工", { securityLevel: "一级" }),
  f("SYS_BRANCH", "系统分支", "VARCHAR2(100)", "系统分支标识", { securityLevel: "一级" }),
];

/** 用车管理系统 TWB_CAR_APPLY_I — 完整 15 项字段（与业务数据字典一致） */
const CAR_APPLY_FIELDS = [
  f("SQRQ", "申请日期", "DATE", "申请提交日期", { highlighted: true }),
  f("SQID", "申请单编号", "VARCHAR", "用车申请单号", { isPk: true, highlighted: true }),
  f("LY", "用车理由", "VARCHAR", "申请事由", { highlighted: true }),
  f("APPLYTYPE", "用车类型", "VARCHAR", "公务/生产等用车类型", { highlighted: true }),
  f("YCRLXDH", "申请人联系电话", "VARCHAR", "申请人联系电话", { highlighted: true }),
  f("SQRQ", "申请日期", "DATE", "申请日期（申请单表）"),
  f("APPLYTYPE", "用车类型", "VARCHAR", "用车类型（申请单表）"),
  f("LY", "用车理由", "VARCHAR", "用车理由（申请单表）"),
  f("SFPC", "是否派车", "VARCHAR", "是否已派车：是/否"),
  f("SFWF", "是否往返", "VARCHAR", "是否往返：单程/往返"),
  f("CFD", "出发地", "VARCHAR", "出发地点", { highlighted: true }),
  f("LOCATION", "途经点", "VARCHAR", "途经地点"),
  f("MDD", "目的地", "VARCHAR", "目的地点", { highlighted: true }),
  f("KSSJ", "出发时间", "TIMESTAMP", "用车出发时间", { highlighted: true }),
  f("JSSJ", "回场时间", "TIMESTAMP", "用车回场/结束时间", { highlighted: true }),
];

/** 八类无感数据源元信息 + 完整字段结构 */
export const SENSING_ACCESS_SOURCES = [
  {
    code: "online_travel",
    name: "南网商旅通",
    shortName: "商旅通",
    category: "online",
    sourceTable: "TWB_T_TRAVEL_TRAVEL_APPLY_I",
    description: "南网商旅通出差申请数据，含差旅人员、行程、审批及费用信息（共66项字段）",
    fields: TRAVEL_APPLY_FIELDS,
    defaultMobile: { syncFreq: "每4小时同步", status: "sync", apiPath: "南网数据中心接入" },
    defaultWeb: { syncFreq: "每2小时同步", status: "sync", apiPath: "南网数据中心接入" },
  },
  {
    code: "online_learn",
    name: "南网智学",
    shortName: "智学培训",
    category: "online",
    sourceTable: "TWC_HR_TRAIN_CLASS_STUDENT_HOURS_QTY_I",
    description: "南网智学平台员工培训学时、方式及组织信息（共44项字段）",
    fields: LEARN_TRAINING_FIELDS,
    defaultMobile: { syncFreq: "每6小时同步", status: "sync", apiPath: "南网数据中心接入" },
    defaultWeb: { syncFreq: "每4小时同步", status: "sync", apiPath: "南网数据中心接入" },
  },
  {
    code: "online_login",
    name: "数认平台登录记录",
    shortName: "数认登录",
    category: "online",
    sourceTable: "TB_LOGIN_LOG",
    description: "数认平台用户登录行为日志",
    fields: [
      f("SCOPE", "作用域", "VARCHAR(64)", "作用域：bpc、app[应用中心]"),
      f("CREATE_TIME", "创建时间", "TIMESTAMP(8)", "登录时间", { highlighted: true }),
      f("USER_ID", "用户id", "VARCHAR(64)", "登录用户标识", { highlighted: true }),
      f("USER_NAME", "用户名", "VARCHAR(64)", "登录账号", { highlighted: true }),
      f("FULL_NAME", "姓名", "VARCHAR(64)", "用户姓名", { highlighted: true }),
      f("MESSAGE", "登录信息", "VARCHAR(255)", "登录结果/描述", { highlighted: true }),
      f("IP", "ip", "VARCHAR(64)", "登录IP地址"),
      f("CREATE_BY", "创建人", "VARCHAR(64)", "记录创建人"),
    ],
    defaultMobile: { syncFreq: "实时同步", status: "sync", apiPath: "南网数据中心接入" },
    defaultWeb: { syncFreq: "实时同步", status: "sync", apiPath: "南网数据中心接入" },
  },
  {
    code: "online_leave",
    name: "人资休假台账",
    shortName: "休假台账",
    category: "online",
    sourceTable: "HR_STAFF_HUMAN_HOLIDAY",
    description: "人资系统员工休假申请、审批、销假及流程信息（共50项字段）",
    fields: LEAVE_LEDGER_FIELDS,
    defaultMobile: { syncFreq: "每8小时同步", status: "sync", apiPath: "南网数据中心接入" },
    defaultWeb: { syncFreq: "每4小时同步", status: "sync", apiPath: "南网数据中心接入" },
  },
  {
    code: "online_workticket",
    name: "电网管理平台资产域（工作票）",
    shortName: "工作票",
    category: "online",
    sourceTable: "TWC_SP_PD_REPAIR_PLAN_DET_A",
    description: "电网管理平台资产域作业计划与工作票执行数据（共128项字段）",
    fields: WORK_TICKET_FIELDS,
    defaultMobile: { syncFreq: "每2小时同步", status: "sync", apiPath: "南网数据中心接入" },
    defaultWeb: { syncFreq: "每1小时同步", status: "sync", apiPath: "南网数据中心接入" },
  },
  {
    code: "online_car",
    name: "用车管理系统",
    shortName: "用车管理",
    category: "online",
    sourceTable: "TWB_CAR_APPLY_I",
    description: "用车申请单数据，含行程、派车及时间信息（共15项字段）",
    fields: CAR_APPLY_FIELDS,
    defaultMobile: { syncFreq: "每4小时同步", status: "sync", apiPath: "南网数据中心接入" },
    defaultWeb: { syncFreq: "每2小时同步", status: "sync", apiPath: "南网数据中心接入" },
  },
  {
    code: "offline_canteen",
    name: "食堂用餐记录",
    shortName: "食堂用餐",
    category: "offline",
    sourceTable: "食堂消费导入表",
    description: "线下导入的食堂早/中/晚餐刷卡用餐记录",
    fields: [
      f("name", "姓名", "字符串", "员工姓名", { highlighted: true }),
      f("phone", "电话", "字符串", "联系电话", { highlighted: true }),
      f("idCard", "员工身份证号", "字符串", "员工身份证号码", { highlighted: true }),
      f("orgName", "所属组织机构", "字符串", "所属部门/机构", { highlighted: true }),
      f("mealTime", "时间", "日期时间", "用餐时间", { highlighted: true }),
      f("breakfast", "食堂早餐用餐记录", "日期时间", "早餐刷卡时间", { highlighted: true }),
      f("lunch", "食堂午餐用餐记录", "日期时间", "午餐刷卡时间", { highlighted: true }),
      f("dinner", "食堂晚餐用餐记录", "日期时间", "晚餐刷卡时间", { highlighted: true }),
    ],
    defaultMobile: { syncFreq: "每日同步", status: "sync", apiPath: "单位线下自行导入" },
    defaultWeb: { syncFreq: "每日同步", status: "sync", apiPath: "单位线下自行导入" },
  },
  {
    code: "offline_gate",
    name: "闸机门禁数据",
    shortName: "闸机门禁",
    category: "offline",
    sourceTable: "闸机通行导入表",
    description: "线下导入的闸机进出场通行记录",
    fields: [
      f("name", "姓名", "字符串", "员工姓名", { highlighted: true }),
      f("phone", "电话", "字符串", "联系电话", { highlighted: true }),
      f("idCard", "员工身份证号", "字符串", "员工身份证号码", { highlighted: true }),
      f("orgName", "所属组织机构", "字符串", "所属部门/机构", { highlighted: true }),
      f("passTime", "时间", "日期时间", "通行时间", { highlighted: true }),
      f("entryTime", "闸机进入时间记录", "日期时间", "进场刷卡时间", { highlighted: true }),
      f("exitTime", "闸机出去时间记录", "日期时间", "出场刷卡时间", { highlighted: true }),
    ],
    defaultMobile: { syncFreq: "每30分钟同步", status: "sync", apiPath: "单位线下自行导入" },
    defaultWeb: { syncFreq: "每30分钟同步", status: "sync", apiPath: "单位线下自行导入" },
  },
];

export function getAccessSourceByCode(code) {
  return SENSING_ACCESS_SOURCES.find((s) => s.code === code);
}

export function getAccessSourceByName(name) {
  return SENSING_ACCESS_SOURCES.find((s) => s.name === name);
}

export function getAccessSourceDisplayFields(source) {
  return (source && source.fields) || [];
}

/** 按数据源名称返回全部字段中文名（用于外部字段映射下拉） */
export function getAccessSourceFieldLabelsByName(name) {
  const source = getAccessSourceByName(name);
  return (source?.fields || []).map((f) => f.zh).filter(Boolean);
}

export function getHighlightedFieldCount(source) {
  return (source.fields || []).filter((x) => x.highlighted).length;
}
