/**
 * 电网管理平台资产域（工作票）— 完整 128 项字段（与业务数据字典一致）
 */

function f(en, zh, type, meaning, opts = {}) {
  return {
    en,
    zh,
    type,
    meaning,
    isPk: !!opts.isPk,
    securityLevel: opts.securityLevel || "二级",
    highlighted: !!opts.highlighted,
  };
}

const ROWS = [
  ["PLAN_TASK_DOMAIN_NAME", "作业域名称", "CHARACTER VARYING(36)", "作业域名称"],
  ["IS_NEED_MONITOR", "是否纳入视频监控", "CHARACTER VARYING(8)", "是否纳入视频监控"],
  ["WORK_TEAM_FULL_PATH_NAME", "工作班组全路径", "CHARACTER VARYING(2000)", "工作班组全路径"],
  ["CREATOR_UID", "创建人标识", "CHARACTER VARYING(54)", "创建人标识"],
  ["WORK_NEED_COUNT", "工作预计人数", "NUMERIC(4,0)", "工作预计人数"],
  ["PLAN_TASK_TYPE_NAME", "作业任务类型名称", "CHARACTER VARYING(32)", "作业任务类型名称"],
  ["MONITOR_OPINION_CODE", "班组评价编码", "CHARACTER VARYING(15)", "班组评价(1:优, 2:良, 3:中, 4:差)"],
  ["PROV_ORG_NAME", "省级组织名称", "CHARACTER VARYING(128)", "南方电网公司二级组织单位名称"],
  ["DEFECT_CODE", "关联缺陷单编号集合", "CHARACTER VARYING(1000)", "关联缺陷单编号，多个编号用';'隔开"],
  ["PLAN_STATE_NAME", "计划状态名称", "CHARACTER VARYING(64)", "计划状态名称"],
  ["WORK_MEMBER_UNAMES", "工作成员名称集合", "CHARACTER VARYING(2250)", "工作成员名称集合"],
  ["WORK_SITE_NAMES", "工作地点名称集合", "CHARACTER VARYING(4500)", "工作地点名称集合"],
  ["WORK_TYPE_NAME", "工作类别名称", "CHARACTER VARYING(64)", "工作类别名称"],
  ["PROV_ORG_CODE", "省级组织编码", "CHARACTER VARYING(16)", "南方电网公司二级组织单位编码"],
  ["TEMP_TASK_REASON", "临时性作业任务原因", "CHARACTER VARYING(1000)", "临时性作业任务原因"],
  ["WORK_DAY", "工期(天)", "NUMERIC(10,0)", "工期(天)"],
  ["RG_LIGHT_FLAG", "红绿灯标识", "CHARACTER VARYING(64)", "生产计划红绿灯：蓝灯即将开始、黄灯已开始、绿灯按期完成、红灯超期"],
  ["AFFIRM_UID", "确认人标识", "CHARACTER VARYING(54)", "确认人标识"],
  ["WORK_TEAM_OID", "工作班组标识", "CHARACTER VARYING(54)", "工作班组标识"],
  ["START_WORK_TIME", "开工时间", "TIMESTAMP WITHOUT TIME ZONE", "开工时间"],
  ["FLOW_STATE_CODE", "工作流状态编码", "NUMERIC(2,0)", "工作流状态(0:未上报 1:审批中 2:已审批)"],
  ["WORK_RESULT", "工作结果", "CHARACTER VARYING(4500)", "工作结果"],
  ["PLAN_RES_DATE", "计划发布日期", "TIMESTAMP WITHOUT TIME ZONE", "计划发布日期"],
  ["EXECUTE_STATE_CODE", "执行中状态编码", "NUMERIC(1,0)", "执行中状态编码"],
  ["AFFIRM_UNAME", "确认人名称", "CHARACTER VARYING(225)", "确认人名称"],
  ["RISK_LEVEL_NAME", "风险等级名称", "CHARACTER VARYING(32)", "风险等级名称"],
  ["MAINTAIN_SMALL_TYPE_NAME", "超高压九防特巡类别名称", "CHARACTER VARYING(54)", "超高压九防特巡类别名称"],
  ["TW_INSERT_TIME", "入仓时间", "TIMESTAMP WITHOUT TIME ZONE", "记录数据加载到表中的时间"],
  ["SPECIALITY_CODE", "当前专业编码", "NUMERIC(4,0)", "当前专业(1调度2变电运行3输电4检修5继保6配电等)"],
  ["WORK_MASTER_PHONE", "工作负责人电话", "CHARACTER VARYING(20)", "工作负责人电话"],
  ["PATROL_OBJECT_SELECT_TYPE_NAME", "巡视对象选择类型名称", "CHARACTER VARYING(128)", "巡视对象选择类型名称"],
  ["JOB_CONTENT", "工作内容", "CHARACTER VARYING(8168)", "工作内容"],
  ["DISPATCH_WORK_UNAME", "派工人员名称", "CHARACTER VARYING(150)", "派工人员名称"],
  ["REAL_BEGIN_TIME", "实际开始时间", "TIMESTAMP WITHOUT TIME ZONE", "实际开始时间", { highlighted: true }],
  ["EXECUTE_STATE_NAME", "执行中状态名称", "CHARACTER VARYING(36)", "执行中状态名称"],
  ["PROCESS_INS_ID", "流程实例标识", "CHARACTER VARYING(60)", "流程实例标识"],
  ["IS_ADD_WORKWRIT", "是否办票", "CHARACTER VARYING(16)", "是否办票"],
  ["OUTAGE_CODE", "关联停电申请单编号集合", "CHARACTER VARYING(30000)", "关联停电申请单编号，多个编号用';'隔开"],
  ["SPECIALITY_BIG_CODE", "专业大类编码", "NUMERIC(2,0)", "专业大类"],
  ["DATEEXTEND1", "日期型扩展字段1", "DATE", "日期型扩展字段1"],
  ["DATEEXTEND2", "日期型扩展字段2", "DATE", "日期型扩展字段2"],
  ["RUNMANAGE_TEAM_UNAME", "运行班组名称", "CHARACTER VARYING(225)", "运行班组名称"],
  ["DEPT_ORG_CODE", "部门(供电所)组织编码", "CHARACTER VARYING(16)", "南方电网公司五级组织单位编码"],
  ["IS_NEED_AUDIT_TEMP_TASK", "需审批的临时任务", "CHARACTER VARYING(8)", "需审批的临时任务(1:是)"],
  ["NOT_APPLY_OUTAGE", "是否无须报停电", "NUMERIC(2,0)", "无须报停电(1:是)"],
  ["REAL_END_TIME", "实际结束时间", "TIMESTAMP WITHOUT TIME ZONE", "实际结束时间", { highlighted: true }],
  ["RUNMANAGE_TEAM_OID", "运行班组标识", "CHARACTER VARYING(36)", "运行班组标识"],
  ["COUNTY_ORG_CODE", "县(区)局组织编码", "CHARACTER VARYING(16)", "南方电网公司四级组织单位编码"],
  ["TW_CREATE_NAME", "开发人员名称", "CHARACTER VARYING(64)", "数据仓库开发人员名称"],
  ["CREATOR_UNAME", "创建人名称", "CHARACTER VARYING(192)", "创建人名称"],
  ["EXTERIOR_DEPT_NAME", "外单位名称", "CHARACTER VARYING(225)", "外单位名称"],
  ["PLAN_EXPIRE_DATE", "计划到期日期", "TIMESTAMP WITHOUT TIME ZONE", "计划到期日期"],
  ["RISK_LEVEL_CODE", "风险等级编码", "NUMERIC(2,0)", "风险等级(1特高2高3中4低5可接受)"],
  ["PLAN_STATE_CODE", "计划状态编码", "NUMERIC(4,0)", "计划状态(10新增20审批中30待发布40已发布50执行中60待确认70已完成80变更中90已取消)"],
  ["PLAN_BEGIN_TIME", "计划开始时间", "TIMESTAMP WITHOUT TIME ZONE", "计划开始时间"],
  ["UPDATE_TIME", "数据更新时间", "TIMESTAMP WITHOUT TIME ZONE", "更新时间"],
  ["PLAN_BEGIN_WEEK_NAME", "计划开始时间所在星期名称", "CHARACTER VARYING(16)", "计划开始时间所在星期名称"],
  ["WORK_MASTER_UID", "工作负责人标识", "CHARACTER VARYING(54)", "工作负责人标识"],
  ["PATROL_MODE_NAME", "巡视方式名称", "CHARACTER VARYING(128)", "巡视方式名称"],
  ["VOLTAGE_GRADE_ID", "基准电压等级标识", "CHARACTER VARYING(30)", "基准电压等级标识"],
  ["SPECIALITY_NAME", "当前专业名称", "CHARACTER VARYING(36)", "当前专业名称"],
  ["COUNTY_ORG_NAME", "县(区)局组织名称", "CHARACTER VARYING(128)", "南方电网公司四级组织单位名称"],
  ["FLOW_STATE_NAME", "工作流状态名称", "CHARACTER VARYING(32)", "工作流状态名称"],
  ["STRINGEXTEND2", "字符型扩展字段2", "CHARACTER VARYING(4000)", "字符型扩展字段2"],
  ["STRINGEXTEND1", "字符型扩展字段1", "CHARACTER VARYING(4000)", "字符型扩展字段1"],
  ["STRINGEXTEND4", "字符型扩展字段4", "CHARACTER VARYING(4000)", "字符型扩展字段4"],
  ["STRINGEXTEND3", "字符型扩展字段3", "CHARACTER VARYING(4000)", "字符型扩展字段3"],
  ["STRINGEXTEND5", "字符型扩展字段5", "CHARACTER VARYING(4000)", "字符型扩展字段5"],
  ["IMPLEMENT_MODE_NAME", "实施方式名称", "CHARACTER VARYING(32)", "实施方式名称"],
  ["ID", "主键", "CHARACTER VARYING(300)", "主键", { isPk: true }],
  ["EXECUTE_DOWNLOAD_STATE_CODE", "执行环节下载状态编码", "NUMERIC(1,0)", "执行环节下载状态(1未下载2已下载3已上传)"],
  ["POWER_GRID_NAME", "主网网架名称", "CHARACTER VARYING(16)", "主网网架名称"],
  ["WORK_TEAM_ORG_NAME", "工作班组名称", "CHARACTER VARYING(450)", "工作班组名称"],
  ["PLAN_SOURCE_TYPE_NAME", "计划来源类型名称", "CHARACTER VARYING(225)", "计划来源类型名称"],
  ["VOLTAGE_GRADE_NAME", "基准电压等级名称", "CHARACTER VARYING(1000)", "基准电压等级名称"],
  ["WORK_TICKET_ID", "工作票ID", "CHARACTER VARYING(54)", "关联工作票标识", { highlighted: true }],
  ["ORG_CODE", "组织机构编码", "CHARACTER VARYING(16)", "组织机构编码"],
  ["DOMAIN_CONSUME_STATE_NAME", "领域消费状态名称", "CHARACTER VARYING(64)", "领域消费状态名称"],
  ["DOMAIN_CONSUME_STATE_CODE", "领域消费状态编码", "CHARACTER VARYING(16)", "领域消费状态编码"],
  ["IS_DELETED_NAME", "是否删除名称", "CHARACTER VARYING(16)", "是否删除名称"],
  ["IS_DELETED_CODE", "是否删除编码", "CHARACTER VARYING(8)", "是否删除编码"],
  ["PLAN_TYPE_NAME", "计划类型名称", "CHARACTER VARYING(64)", "计划类型名称"],
  ["PLAN_TYPE_CODE", "计划类型编码", "CHARACTER VARYING(16)", "计划类型编码"],
  ["APPROVE_TIME", "审批时间", "TIMESTAMP WITHOUT TIME ZONE", "审批时间"],
  ["REPAIR_TYPE_NAME", "检修类型名称", "CHARACTER VARYING(64)", "检修类型名称"],
  ["REPAIR_TYPE_CODE", "检修类型编码", "CHARACTER VARYING(16)", "检修类型编码"],
  ["WORK_TICKET_NAME", "工作票名称", "CHARACTER VARYING(225)", "工作票名称"],
  ["PLAN_STATE_NAME", "计划状态名称", "CHARACTER VARYING(64)", "计划状态名称（业务表）"],
  ["PLAN_STATE_CODE", "计划状态编码", "NUMERIC(4,0)", "计划状态编码（业务表）"],
  ["END_TIME", "结束时间", "TIMESTAMP WITHOUT TIME ZONE", "结束时间"],
  ["DEPT_ID", "部门ID", "CHARACTER VARYING(54)", "部门标识"],
  ["DEPT_NAME", "部门名称", "CHARACTER VARYING(225)", "部门名称"],
  ["REAL_START_TIME", "实际开始时间", "TIMESTAMP WITHOUT TIME ZONE", "实际开始时间"],
  ["CREATE_TIME", "创建时间", "TIMESTAMP WITHOUT TIME ZONE", "创建时间"],
  ["UPDATE_TIME", "更新时间", "TIMESTAMP WITHOUT TIME ZONE", "更新时间（业务表）"],
  ["POWER_OFF_RANGE", "停电范围", "CHARACTER VARYING(4500)", "停电范围"],
  ["WORK_CONTENT", "工作内容", "CHARACTER VARYING(8168)", "工作内容"],
  ["RATING_ASSET_OBJECT_TYPE_CN", "额定资产对象类型中文", "CHARACTER VARYING(128)", "额定资产对象类型中文"],
  ["PLAN_TIME_START_DATE", "计划时间开始日期", "DATE", "计划时间开始日期"],
  ["PLAN_NATURE_NAME", "计划性质名称", "CHARACTER VARYING(64)", "计划性质名称"],
  ["PLAN_NATURE_CODE", "计划性质编码", "CHARACTER VARYING(16)", "计划性质编码"],
  ["WORK_TASK_TYPE_NAME", "工作任务类型名称", "CHARACTER VARYING(64)", "工作任务类型名称"],
  ["WORK_TASK_TYPE_CODE", "工作任务类型编码", "CHARACTER VARYING(16)", "工作任务类型编码"],
  ["ORG_NAME", "组织机构名称", "CHARACTER VARYING(450)", "组织机构名称"],
  ["SPECIALTY_TYPE_NAME", "专业类型名称", "CHARACTER VARYING(64)", "专业类型名称"],
  ["SPECIALTY_TYPE_CODE", "专业类型代码", "CHARACTER VARYING(16)", "专业类型代码"],
  ["PLAN_TYPE_NAME", "计划类型名称", "CHARACTER VARYING(64)", "计划类型名称（业务表）"],
  ["PLAN_TYPE_CODE", "计划类型编码", "CHARACTER VARYING(16)", "计划类型编码（业务表）"],
  ["REASON_FOR_DELAY", "延期原因", "CHARACTER VARYING(1000)", "延期原因"],
  ["WORK_TICKET_CODE", "工作票编号", "CHARACTER VARYING(64)", "工作票编号", { highlighted: true }],
  ["REAL_END_TIME", "实际结束时间", "TIMESTAMP WITHOUT TIME ZONE", "实际结束时间（业务表）", { highlighted: true }],
  ["REPAIR_PROJECT", "检修项目", "CHARACTER VARYING(4500)", "检修项目"],
  ["ASSET_ID", "资产ID", "CHARACTER VARYING(54)", "资产标识"],
  ["ASSET_NAME", "资产名称", "CHARACTER VARYING(450)", "资产名称"],
  ["VOLTAGE_LEVEL_NAME", "电压等级名称", "CHARACTER VARYING(64)", "电压等级名称"],
  ["VOLTAGE_LEVEL_CODE", "电压等级编码", "CHARACTER VARYING(16)", "电压等级编码"],
  ["STATION_ID", "变电站ID", "CHARACTER VARYING(54)", "变电站标识"],
  ["STATION_NAME", "变电站名称", "CHARACTER VARYING(225)", "变电站名称"],
  ["BAY_ID", "间隔ID", "CHARACTER VARYING(54)", "间隔标识"],
  ["BAY_NAME", "间隔名称", "CHARACTER VARYING(225)", "间隔名称"],
  ["DEVICE_ID", "设备ID", "CHARACTER VARYING(54)", "设备标识"],
  ["DEVICE_NAME", "设备名称", "CHARACTER VARYING(450)", "设备名称"],
  ["PLAN_TIME_END_DATE", "计划时间结束日期", "DATE", "计划时间结束日期"],
  ["IS_URGENT_NAME", "是否紧急名称", "CHARACTER VARYING(16)", "是否紧急名称"],
  ["WORK_TASK_TYPE_CODE", "工作任务类型编码", "CHARACTER VARYING(16)", "工作任务类型编码（业务表）"],
  ["REPAIR_LEVEL_NAME", "检修级别名称", "CHARACTER VARYING(64)", "检修级别名称"],
  ["REPAIR_LEVEL_CODE", "检修级别编码", "CHARACTER VARYING(16)", "检修级别编码"],
  ["PLAN_TIME_START_DATE", "计划时间开始日期", "DATE", "计划时间开始日期（业务表）"],
];

export const WORK_TICKET_FIELDS = ROWS.map((row) => {
  const [en, zh, type, meaning, opts = {}] = row;
  return f(en, zh, type, meaning, opts);
});
